apiVersion: v1
kind: Secret
metadata:
  name: infravision-secrets
  namespace: infravision
type: Opaque
stringData:
  ConnectionStrings__Postgres: "Host=postgres.database.svc.cluster.local;Port=5432;Database=infravision;Username=infravision;Password=CHANGE_ME_DB_PASSWORD"
  Jwt__Key: "CHANGE_ME_JWT_KEY_32_CHARS_MIN"
  Jwt__Issuer: "InfraVision"
  Jwt__Audience: "InfraVisionUsers"
  Jwt__ExpiryMinutes: "60"
  AdminUser__Username: "admin"
  AdminUser__Password: "CHANGE_ME_ADMIN_PASSWORD"
