apiVersion: v1
kind: Secret
metadata:
  name: infravision-secrets
  namespace: infravision
type: Opaque
stringData:
  ConnectionStrings__Postgres: "Host=postgres.database.svc.cluster.local;Port=5432;Database=infravision;Username=infravision;Password=infravision123"
  Jwt__Key: "CHANGE_ME_super_secret_key_at_least_32_chars_long!!"
  Jwt__Issuer: "InfraVision"
  Jwt__Audience: "InfraVisionUsers"
  Jwt__ExpiryMinutes: "60"
  AdminUser__Username: "admin"
  AdminUser__Password: "InfraVision2026!"
