apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infravision-api
  namespace: infravision
spec:
  ingressClassName: nginx
  rules:
    - host: infravision.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: infravision-api
                port:
                  number: 80
