apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: database
type: Opaque

stringData:
  POSTGRES_USER: infravision
  POSTGRES_PASSWORD: CHANGE_ME_DB_PASSWORD
  POSTGRES_DB: infravision
